### PR TITLE
Amalgamate color_mode's into a single location

### PR DESCRIPTION
**Pull request by stephen322**
No need to merge this.  But looking for feedback into whether I should run with this idea or not.

Plan is to amalgamate as much color_mode code into a single location as possible, to allow for easier addition of a color_mode for the next person, as well as clean up some hard-to-read logic.

This would require a significant reorganization of code in visualizer.py and settings in various places, but I don't want to step on anyone's toes.  I can try it if this would be beneficial.

### CODE REVIEW

**Comment by onlaj** [comment]
I agree, this is what this code needs.
I should have started refactoring the code much earlier. The current pattern worked well when it was used to display a smaller number of different color modes. Currently there are too many of them and it becomes illegible.

If you feel that this commit is a good basis for further work, I can merge it into a separate branch.

**Comment by stephen322** [comment]
Hmm, up to you on how you want to manage it.  I can either build on this, or rebase it once it actually does something and looks closer to its final implementation.  Either way is okay with me.

**Comment by stephen322** [comment]
This branch is ready for review.
Two changes unrelated to color_mode (and light mode) rewrites:
1) Rainbow color timeshift fix under Normal fade/light mode
2) Bug fix websettings: will re-init ledsettings, which can cause crashes/problems.

Plan was to continue amalgamating color_mode settings in a dynamically configured way based solely on xml config, and remove much of the manual configuration in ledsettings, but if I get around to it, it can be a different pull request.

**Review by onlaj — APPROVED** [review]
I tested all affected settings in various combinations. Everything seems to be working as before, but now it's much more readable, great work!

**Pull request merged**
