### PR TITLE
Added visualizer update

### PR DESCRIPTION
**Pull request by EmanuelFeru**
- the visualizer can now be updated from the menu options without the need of SSH connection

### CODE REVIEW

**Comment by onlaj** [comment]
What if someone didn't set their identity? On my Pi I didn't configure git and I get "Please tell me who you are." error.

StEiFUf

Any idea how to bypass that?

**Comment by EmanuelFeru** [comment]
For me it did not complain, even though I have empty name and email. I added dummy name and email as commands
Can you try the last commit?

**Comment by onlaj** [comment]
I'm getting conflict errors because of unmerged files. I think the same thing will happen to people with local changes. Maybe there should be
`git reset --hard HEAD`
command to discard all local changes before pull?

**Comment by EmanuelFeru** [comment]
We can try. I think if we do the hard reset, then we can remove the name and email setting.

**Comment by onlaj** [comment]
Now it seems to be okay, can you confirm it works for you too? 
Should it look like this?
```
HEAD is now at 8f6ce82 Reversed Led strip (#204)
Removing __pycache__/
Removing tests/rtpmidi.py
From https://github.com/onlaj/Piano-LED-Visualizer
 * branch            master     -> FETCH_HEAD
Already up to date.
```

**Comment by EmanuelFeru** [comment]
Yes, I have the same. Nice to see it works. I hope I did not delete your work in `rtpmidi.py` with this :)

**Comment by onlaj** [comment]
> I hope I did not delete your work in rtpmidi.py with this :)

Nah, I have it locally on my pc. Well done, merging ;)

**Pull request merged**
