### PR TITLE
Adding Natural minor scales

### PR DESCRIPTION
**Pull request by CriToX42**
New scales added: patern: T-S-T-T-S-T-T
T=Tone (whole-tone)
S=Semi-tone (half-tone)
for more info on this: https://www.damvibes.com/music-theory/minor-scales/

These scales are some of the most used one.
It may be needed to add an extra menu in order to choose wich types of scale we want (major, natural minor, harmonic minor, melodic minor, dorian ...)

### CODE REVIEW

**Comment by onlaj** [comment]
Thank you for your contribution and sorry for the late reply.
I ordered new RPi (old one is fried) and I will try to test your PR this week.

In web interface the new scales are called just "C", "C#" etc. Shouldn't it be "C m", "C# m" and so on, like in screen's menu?
Anyway, it looks like a useful feature, I will read more about those scales and merge the PR after testing.

**Comment by CriToX42** [comment]
Oh you're right, it's fixed, Do you know any way to update the raspberry with you're own code in order to test it ? ( I men another way than with putting back the sd card in another pc)

**Comment by CriToX42** [comment]
Oh you're right, it's fixed, Do you know any way to update the raspberry with you're own code in order to test it ? ( I men another way than with putting back the sd card in another pc)

**Comment by onlaj** [comment]
You would have to connect to your RPi with SFTP to send files and then SSH to it to start the script.

**Comment by CriToX42** [comment]
Ok, thanks, i'll check that when i'll be back home.

**Pull request merged**
