### PR TITLE
Learning without Synthesia (#180)

### PR DESCRIPTION
**Pull request by EmanuelFeru**
Major:
- created Learning MIDI without Synthesia #180 
- increased the delay for KEYLEFT and KEYRIGHT from 0.02 to 0.1 to be able to easily choose values
- added `clamp` function
- added `get_note_position` function

Minor:
- clean-up of white spaces in the code
- added test file learnmidi.py
- added 2 new midi files
- updated ReadMe

### CODE REVIEW

**Comment by onlaj** [comment]
Wow, that's a big commit :D 
I didn't go deep into the code yet, but I fetched the PR and I'm testing it now. Your example midi files works fine, but I tried some of my own and one didn't even wanted to start. When I press "Start learn" the arrow goes there for a split second and then goes back to "Stop learn", it plays fine with my "Play MIDI" function tho.
With other files I had problems with proper keys not lighting at all on some notes.
Maybe it's a problem with midi files itself, I can send them if you want to test them.
Overall, with proper midi files, it works very well.
A small QOL change would be to add "End point" as an addition to "Start point", so you can practice specific parts of songs. It would also be useful to have an option to pick both start and end points while playing.

**Comment by EmanuelFeru** [comment]
Yes, can you send me the files so I can try? I only used Type 1 midi files and maybe you have different ones, so I need to check them what is inside and how they are structured. The fact that the arrow jumps back to Stop is an  indication that it couldn't load or process the file.

End point can be added, however there is only one free position available in the menu and I would prefer to have everything in one page. We can give it a try and see. For adjusting Start point while playing you can already do that, but I'm not sure if it is picked up by the for loop, because i basically change the index of the list. Need to be checked.


And sorry for the big commit, I tried to improve also other parts of the code along the way :). I have some suggestions for future improvement, we can discuss later. Basically, it would be ideal and much easier to navigate throughout the code if we split the visualizer.py into: 
- `visualizer.py` (as the main file where all the files connect with each other)
- `ledstrip.py` (contains all the code related to the LED strip)
- `userinterface.py` (code for the menu, screen and buttons handling)
- `midiutils.py` (contains all midi related code)

**Comment by onlaj** [comment]
Here is the [file](https://securesha.re?#u=cd426f4b08ed04dc32aa5942e44ceaf2.bin&p=sazBbLhhidNRwyJjf_g-EUdaR0UZB80E/wfCiPfXJ6E) 
I'm not sure if it's not copyrighted so I set it to autodelete after 24 hours.

Yeah, I was also thinking about spliting classes into separate files since they have grown so much.

**Comment by EmanuelFeru** [comment]
Just quickly checked the file you sent, it is still Type 1, but the Right hand = Track 1 and Left hand = Track 2. I will think how can I differentiate between the 2, so we can use both. By the way I like the song :)

image

vs mine (currently supported)
image

**Comment by EmanuelFeru** [comment]
Fixed the midi file in the last commit. For me it works, can you confirm it works for you?
You also said you had a file that was not even loading, is that still the case?
I also added some other stuff you proposed, I hope you like it :)

**Comment by onlaj** [comment]
Well done! :)

> You also said you had a file that was not even loading, is that still the case?

The one I sent you was not loading. I also had problems with original example midi, la campanella, now it works fine.
I'm ready to merge unless you want to add or change something.

**Comment by EmanuelFeru** [comment]
I am happy that you like it! I also think it came out quite nice, it is like a push from the back when playing, at least for me, as I am a beginer. So, for me it is ok to merge.
Let's discuss later for splitting into different files.

**Pull request merged**
