### PR TITLE
Colors for scales

### PR DESCRIPTION
**Pull request by SivanDuijn**
Added a menu in LED Color for Scale Coloring. Here you can select the scale and colors. Only major scales.

I did test it and it is seems to work fine.

### CODE REVIEW

**Comment by onlaj** [comment]
Putting it in the words of a person with almost no music education, this feature makes the black keys lights with a different color to the white ones, right?

**Comment by SivanDuijn** [comment]
yes, kinda, its a pull request for this feature request [https://github.com/onlaj/Piano-LED-Visualizer/issues/182](url)
But i don't know how to link them properly.

afbeelding
If you would select the C scale. Then yes, the white keys will have a different color than the black keys. But you could also select a different scale

**Comment by onlaj** [comment]
>It's more an educational feature than an aesthetically pleasing one.

I see, then there is no need for adding support to record those colors on different midi files.
I will make some additional tests and then merge it, thanks for your contribution!

**Comment by SivanDuijn** [comment]
No i don't think so. You can record color with midi files? Cool, didn't know that.
Glad to contribute!

**Pull request merged**
